### PR TITLE
fix: [#1549] Remove unecessary sprite effect for opacity

### LINKED ISSUE #1549: Opacity sprite effect is unnecessary and causes perf degradation
### Steps to Reproduce
When adding a new drawing to excalibur it currently triggers sprite effect calculations on opacity (whether or not it needs it). Additionally there is no need to use sprite effects for opacity anymore.

image

### PR DESCRIPTION
**Pull request by eonarheim**
===:clipboard: PR Checklist :clipboard:===

- [x] :pushpin: issue exists in github for these changes
- [x] :microscope: existing tests still pass
- [x] :see_no_evil: code conforms to the [style guide](https://github.com/excaliburjs/Excalibur/blob/master/STYLEGUIDE.md)
- [x] :triangular_ruler: new tests written and passing / old tests updated with new scenario(s)
- [x] :page_facing_up: changelog entry added (or not needed)

==================

Closes #1549

## Changes:

- Remove opacity sprite effect from actor
- Only process effects if necessary

### CODE REVIEW

**Comment by eonarheim** [comment]
@kamranayub Definitely, just haven't had time yet 👍

File: src/engine/Drawing/Animation.ts [hunk 1]
```diff
@@ -277,24 +280,35 @@ export class AnimationImpl implements Drawable {
...
+      this._drawWithOptions({ ctx: ctxOrOptions, x, y });
     } else {
       this._drawWithOptions(ctxOrOptions);
     }
   }
 
   private _drawWithOptions(options: DrawOptions) {
+    const animOptions = {
+      ...options,
+      rotation: nullish(options.rotation, this.rotation),
```
Comment (kamranayub) [inline src/engine/Drawing/Animation.ts:292]: Does nullish account for 0 number or empty strings, since those aren't nullish? Sorry, I can't see the impl easily on my phone

**Comment by kamranayub** [comment]
Okay I looked at the impl, question though: with TS 3.9 can we just use null coalescing? It would let us do the same right?

**Comment by eonarheim** [comment]
> Okay I looked at the impl, question though: with TS 3.9 can we just use null coalescing? It would let us do the same right?

You are correct, I think `nullish()` was added to excalibur before `??` was at the final stage. Definitely will change it before merging

**Comment by eonarheim** [comment]
@kamranayub Updated :+1:
