### PR TITLE
[#908] Fix BaseCamera documentation

### LINKED ISSUE #908: Documentation on ex.BaseCamera is wrong for `setActorToFollow`
### Steps to Reproduce
See this google groups thread: https://groups.google.com/forum/#!topic/excaliburjs/KqqqgCw-B14

BaseCamera.setActorToFollow does not actually get the camera to follow an actor must replace the current camera implementation with `ex.LockedCamera` for it to work.

```typescript
game.currentScene.camera = new ex.LockedCamera();
game.currentScene.camera.setActorToFollow(actor);
```
See pen with working example on latest ex:
https://codepen.io/eonarheim/pen/gXogGp?editors=0010

### Expected Result
BaseCamera.setActorToFollow documenation should outline the process to get this to work, or we should deprecate it. Or update the BaseCamera implementation to support this.

### Actual Result
Following the documentation did not work

### PR DESCRIPTION
**Pull request by eonarheim**
Closes #908

## Changes:

- Updates documentation to clarify current process
- Kill some dead code in `BaseCamera`
- Removes `setActorToFollow` method on `BaseCamera` that doesn't work when set and is confusing

### CODE REVIEW

File: src/engine/Camera.ts [hunk 1]
```diff
@@ -88,14 +87,6 @@ export class BaseCamera {
       }
    }
 
-   /**
```
Comment (jedeen) [inline src/engine/Camera.ts]: This is a breaking change, and should be documented in the changelog.

Comment (eonarheim) [reply src/engine/Camera.ts]: Actually no, it was dead code, did nothing
