### PR TITLE
Catch global errors

### LINKED ISSUE #381: Catch global (fatal) errors to aid in debugging
Exascerbated by mobile, update loop errors can cause crashing and are hard to debug. Can we figure out a way to intelligently catch errors in update loop and break/stop the game execution so it doesn't wedge browsers?

```
mainloop() {

  try {
    engine.update(delta);
  } catch (e) {
    // update loop error, catch and rethrow safely with debugging info
   cancelRequestAnimationFrame(mainloop);
  }
}
```

### PR DESCRIPTION
**Pull request by jedeen**
closes #381

### CODE REVIEW

File: src/engine/Engine.ts [hunk 1]
```diff
@@ -1016,24 +1024,30 @@ module ex {
...
+                  // into focus
+                  if(elapsed > 200) {
+                     elapsed = 1;
+                  }
+                  game._update(elapsed);
+                  game._draw(elapsed);
+   
+                  lastTime = now;
+               
+            } catch (e) {
```
Comment (kamranayub) [inline src/engine/Engine.ts]: This line through 1050 is mis-indented. Needs one more push!

**Comment by kamranayub** [comment]
Looks good to me, besides the minor indent.
