### PR TITLE
Fix camera lerp and support easing functions

### LINKED ISSUE #555: Camera lerp only works if you call setFocus
Setting camera.x or camera.y wont work if camera.lerp is set to true. You must call camera.setFocus.

### PR DESCRIPTION
**Pull request by kamranayub**
Closes #555, #320 

Add `camera.move` and support EasingFunctions

- Removed `lerp` property (**breaking change**)
- Removed deprecated `setFocus` method (**breaking change**)
- Added new `move` function to support lerping to a position which returns a `Promise<Vector>`
- Added support for `ex.EasingFunctions`
- Added new interface definition for an `EasingFunction`
- Update tslint and grunt-tslint

### CODE REVIEW

File: src/engine/Camera.ts [hunk 1]
```diff
@@ -126,23 +141,29 @@ module ex {
...
+       * 
+       * @param pos The target position to move to
+       * @param duration The duration in millseconds the move should last
+       * @param [easingFn] An optional easing function ([[ex.EasingFunctions.EaseInOutCubic]] by default)
        */
-      public setFocus(x: number, y: number) {
-         if (!this._follow && !this.lerp) {
-            this.x = x;
-            this.y = y;
+      public move(pos: Vector, duration: number, easingFn: EasingFunction = EasingFunctions.EaseInOutCubic) {
```
Comment (eonarheim) [inline src/engine/Camera.ts]: It would useful if `move` returned a promise that resolved when this movement is complete

File: src/engine/Camera.ts [hunk 2]
```diff
@@ -77,10 +67,11 @@ module ex {
       public rotation: number = 0;
       public rx: number = 0;
 
-
+      private _x: number = 0;
+      private _y: number = 0;
       private _cameraMoving: boolean = false;
       private _currentLerpTime: number = 0;
-      private _lerpDuration: number = 1 * 1000; // 5 seconds
```
Comment (eonarheim) [inline src/engine/Camera.ts]: Oh man, very sad comment. Good catch

File: src/engine/Util/EasingFunctions.ts [hunk 3]
```diff
@@ -1,6 +1,13 @@
 ﻿module ex {
    
    /**
+    * A definition of an EasingFunction. See [[ex.EasingFunctions]].    
+    */
+   export interface EasingFunction { // tslint:disable-line
```
Comment (eonarheim) [inline src/engine/Util/EasingFunctions.ts]: :+1:

File: src/engine/Util/EasingFunctions.ts [hunk 4]
```diff
@@ -42,24 +49,24 @@
...
+      public static Linear: EasingFunction = (currentTime: number, startValue: number, endValue: number, duration: number)  => {
          endValue = (endValue - startValue);
          return endValue * currentTime / duration + startValue;
       };
 
       public static EaseInQuad = (currentTime: number, startValue: number, endValue: number, duration: number) => {
          //endValue = (endValue - startValue);
          currentTime /= duration;
-
+         // TODO implement
```
Comment (eonarheim) [inline src/engine/Util/EasingFunctions.ts]: Should we remove `EaseInQuad` if it is not implemented?

Comment (kamranayub) [inline src/engine/Util/EasingFunctions.ts]: You're currently fixing/fixed this, will wait for your commit

File: src/engine/Camera.ts (hunk 1 above)
Comment (kamranayub) [inline src/engine/Camera.ts]: Fixed
